### ISSUE TITLE
Random numbers not so random

### ISSUE THREAD

**Issue by dvkt** [Lartu/ldpl#90] opened 2019-05-11 19:08 UTC
Maybe the seed is constant by accident? I get the same results each time, it seems:

````
$ cat rand.ldpl 
DATA:
r is number
i is number

PROCEDURE:
while i is less than 5 do
  store random in r
  display r crlf
  incr i
repeat
````
````
$ for i in {1..5}; do echo "# ${i}"; ./rand-bin; done
# 1
0.365382414946976
0.982248013830859
0.642368455250919
0.28662740219693
0.346748723809956
# 2
0.365382414946976
0.982248013830859
0.642368455250919
0.28662740219693
0.346748723809956
# 3
0.365382414946976
0.982248013830859
0.642368455250919
0.28662740219693
0.346748723809956
# 4
0.365382414946976
0.982248013830859
0.642368455250919
0.28662740219693
0.346748723809956
# 5
0.365382414946976
0.982248013830859
0.642368455250919
0.28662740219693
0.346748723809956

**Comment by dgarroDC** [comment] 2019-05-11 20:11
It seems that the problem is that [std::time](https://en.cppreference.com/w/cpp/chrono/c/time) has a resolution on seconds.

**Comment by Lartu** [comment] 2019-05-16 19:18
There, it's fixed now using the C++11 <random> header.

**Closed by Lartu** 2019-05-16 19:18 UTC

**Comment by dvkt** [comment] 2019-05-17 05:18
Works great! :+1:

**Comment by Lartu** [comment] 2019-05-17 05:41
Awesome! :smile:
